# Generated by Django 5.0.4 on 2024-05-02 19:09

import detect_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_app', '0002_uservideo_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.FileField(upload_to='')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_frames', to='detect_app.uservideo')),
            ],
        ),
    ]
