# Generated by Django 5.0.4 on 2024-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_app', '0005_framelabels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framelabels',
            name='labels_txt',
        ),
        migrations.AddField(
            model_name='framelabels',
            name='confidence',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framelabels',
            name='labels',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='framelabels',
            name='h',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='framelabels',
            name='w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='framelabels',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='framelabels',
            name='y',
            field=models.FloatField(),
        ),
    ]
