# Generated by Django 5.0.4 on 2024-05-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect_app', '0006_remove_framelabels_labels_txt_framelabels_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framelabels',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='framelabels',
            name='labels',
        ),
    ]
