# Generated by Django 5.0.4 on 2024-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_app', '0007_remove_framelabels_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='video_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
