# Generated by Django 5.0.4 on 2024-05-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_app', '0008_uservideo_video_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=128)),
                ('class_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='framelabels',
            name='labels_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_labels', to='detect_app.class'),
        ),
    ]
