# Generated by Django 5.0.4 on 2024-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_app', '0009_class_framelabels_labels_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='model_path',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
