# Generated by Django 5.0.4 on 2024-05-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_app', '0010_uservideo_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='framelabels',
            name='track_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
