# Generated by Django 5.0.4 on 2024-05-27 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_app', '0013_detectmodels_remove_uservideo_model_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='model_clases', to='detect_app.detectmodels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
